system:
    default:
        field_templates:
            - {template: '@EzSystemsEzPlatformXmlTextFieldType/content_fields.html.twig', priority: 10}
        fielddefinition_settings_templates:
            - {template: '@EzSystemsEzPlatformXmlTextFieldType/fielddefinition_settings.html.twig', priority: 10}
